# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
    groups:
      root-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'npm'
    directory: '/apps/admin'
    schedule:
      interval: 'weekly'
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
    groups:
      admin-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'npm'
    directory: '/apps/user'
    schedule:
      interval: 'weekly'
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
    groups:
      user-dependencies:
        patterns:
          - "*"

  - package-ecosystem: 'npm'
    directory: '/packages/ui'
    schedule:
      interval: 'weekly'
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
    target-branch: "main"
    groups:
      user-dependencies:
        patterns:
          - "*"
