version: "3.8"

services:
  api:
    container_name: ecommerce
    image: postgres:16
    restart: always
    ports:
      - 8080:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ecommerce:/var/lib/postgresql/data

volumes:
  ecommerce:
