services:
  db:
    container_name: postgres-db
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ecommerce-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ecommerce-pgadmin:/var/lib/pgadmin

  redis:
    container_name: redis-cache
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ecommerce-redis:/var/lib/redis/data

volumes:
  ecommerce-db:
  ecommerce-pgadmin:
  ecommerce-redis:
