import './globals.css';
import '@repo/ui/style.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Toaster } from '@repo/ui/components/toast/toaster';

import AppProvider from '@components/provider';

const roboto = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Capture Digital Shop',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
  sidebar,
  header,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
  header: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider>
          <main className="flex h-[calc(100dvh)] w-full overflow-hidden bg-[#F0F5F4]">
            {sidebar}

            <div className="relative flex flex-1 flex-col overflow-auto pb-10">
              {header}
              {children}
            </div>
          </main>
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
