import './globals.css';
import '@repo/ui/style.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AppProvider from './provider';
import { Toaster } from '@repo/ui/components/toast/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {children}
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
